# Generated by Django 3.1.13 on 2021-08-12 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
