# Generated by Django 3.2.6 on 2021-08-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'banker'), (2, 'customer'), (3, 'funder')], default=2),
        ),
    ]
