# Generated by Django 3.1.13 on 2021-08-12 09:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_auto_20210812_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='started',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 9, 15, 53, 583180, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='loanoption',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
