# Generated by Django 3.1.13 on 2021-08-10 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_auto_20210810_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={},
        ),
        migrations.RemoveField(
            model_name='loan',
            name='duration',
        ),
    ]
