# Generated by Django 3.1.13 on 2021-08-12 09:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_auto_20210812_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='started',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 9, 16, 19, 970782, tzinfo=utc)),
        ),
    ]
