# Generated by Django 3.1.13 on 2021-08-10 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_auto_20210810_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='started',
            field=models.DateField(default=datetime.date(2021, 8, 10)),
        ),
    ]
