# Generated by Django 3.1.13 on 2021-08-10 21:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_loan_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='started',
            field=models.DateField(default=datetime.datetime(2021, 8, 10, 21, 25, 10, 143024, tzinfo=utc)),
        ),
    ]
