# Generated by Django 3.1.13 on 2021-08-12 09:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_auto_20210812_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='started',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 9, 18, 50, 974505, tzinfo=utc)),
        ),
    ]
