# Generated by Django 3.1.13 on 2021-08-11 09:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_auto_20210810_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='duration',
            field=models.CharField(choices=[(1, '6m'), (2, '1y'), (3, '2y')], default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='loan',
            name='started',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 26, 13, 151013, tzinfo=utc)),
        ),
    ]
