# Generated by Django 3.1.13 on 2021-08-11 09:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_auto_20210811_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='duration',
            field=models.CharField(choices=[(1, '6m'), (2, '1y'), (3, '2y')], max_length=2),
        ),
        migrations.AlterField(
            model_name='loan',
            name='started',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 27, 45, 481702, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'banker'), (2, 'customer'), (3, 'funder')], default='customer'),
        ),
    ]
