# Generated by Django 3.1.13 on 2021-08-11 10:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_auto_20210811_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Denied')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='started',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 35, 30, 800071, tzinfo=utc)),
        ),
    ]
