# Generated by Django 3.1.13 on 2021-08-12 18:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0014_auto_20210812_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='started',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 18, 54, 26, 635122, tzinfo=utc)),
        ),
    ]
