# Generated by Django 3.1.13 on 2021-08-13 12:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0026_auto_20210813_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='started',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 13, 12, 31, 18, 216961, tzinfo=utc)),
        ),
    ]
