# Generated by Django 3.1.13 on 2021-08-12 21:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundOption',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('minimum_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('maximum_amount', models.DecimalField(decimal_places=5, max_digits=19)),
                ('duration', models.PositiveIntegerField()),
                ('interest_rate', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=5, max_digits=19)),
                ('started', models.DateTimeField(default=datetime.datetime(2021, 8, 12, 21, 0, 15, 395157, tzinfo=utc))),
                ('status', models.CharField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Denied')], max_length=10)),
                ('fund_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.fundoption')),
                ('funder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
