# Generated by Django 3.1.13 on 2021-08-19 23:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0005_auto_20210813_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='started',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 19, 23, 17, 49, 539329, tzinfo=utc)),
        ),
    ]
