# Generated by Django 3.1.13 on 2021-08-20 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0007_auto_20210820_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='started',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
