# Generated by Django 3.1.13 on 2021-08-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0010_fund_payment_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='payment_receipt_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
